# Generated by Django 5.0 on 2024-09-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram bot user', 'verbose_name_plural': 'Telegram bot users'},
        ),
    ]
