# Generated by Django 5.0 on 2024-09-14 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_moderationforcity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram bot User', 'verbose_name_plural': 'Telegram bot users'},
        ),
        migrations.AlterField(
            model_name='moderationforcity',
            name='admin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Access administrator'),
            preserve_default=False,
        ),
    ]
