# Generated by Django 5.0 on 2024-09-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='main.customuser', verbose_name='Employee')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_assignments', to='main.customuser', verbose_name='Manager')),
                ('mentor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['mentor', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_assignments', to='main.customuser', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Mentorship Assignment',
                'verbose_name_plural': 'Mentorship Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('employee', 'mentor', 'manager')},
            },
        ),
    ]
